#!/bin/sh
set -e
# Automatically added by dh_installinit/12.1.1
if [ -x "/etc/init.d/sonic-platform-semptian-ps7350-32x" ]; then
	invoke-rc.d sonic-platform-semptian-ps7350-32x stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/12.1.1
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'ps7350-32x-driver.service' >/dev/null || true
fi
# End automatically added section
